services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:?error}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    stdin_open: true 
    tty: true 
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3
    networks:
      - app-net

  app-celery-beat:
    build: .
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-net
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TNA_API_KEY=${TNA_API_KEY}
      - CHATGPT_API_KEY=${CHATGPT_API_KEY}
      - NEWS_COUNTRIES=${NEWS_COUNTRIES}
      - NEWS_LANGUAGES=${NEWS_LANGUAGES}
      - CHATGPT_MODEL=${CHATGPT_MODEL}
    volumes:
      - ./:/app
    working_dir: /app
    command: celery -A kidsnews beat -l info

  app-celery-worker:
    build: .
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-net
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TNA_API_KEY=${TNA_API_KEY}
      - CHATGPT_API_KEY=${CHATGPT_API_KEY}
      - NEWS_COUNTRIES=${NEWS_COUNTRIES}
      - NEWS_LANGUAGES=${NEWS_LANGUAGES}
      - CHATGPT_MODEL=${CHATGPT_MODEL}
    volumes:
      - ./:/app
    working_dir: /app
    command: celery -A kidsnews worker -l info

  app:
    build: .
    depends_on:
      - postgres
      - rabbitmq
      - app-celery-worker
    networks:
      - app-net
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TNA_API_KEY=${TNA_API_KEY}
      - CHATGPT_API_KEY=${CHATGPT_API_KEY}
      - NEWS_COUNTRIES=${NEWS_COUNTRIES}
      - NEWS_LANGUAGES=${NEWS_LANGUAGES}
      - CHATGPT_MODEL=${CHATGPT_MODEL}
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"

networks:
  app-net:

volumes:
  pgdata:
    driver: local
