# Generated by Django 5.1 on 2024-09-05 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.UUIDField(unique=True)),
                ('author', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('original_title', models.TextField()),
                ('modified_title', models.TextField(blank=True, null=True)),
                ('original_description', models.TextField(blank=True, null=True)),
                ('modified_description', models.TextField(blank=True, null=True)),
                ('original_content', models.TextField()),
                ('modified_content', models.TextField(blank=True, null=True)),
                ('channel_name', models.CharField(max_length=64)),
                ('channel_response', models.JSONField()),
                ('url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('title_bad_words', models.CharField(blank=True, max_length=200, null=True)),
                ('has_bad_words', models.BooleanField(default=False)),
                ('has_rewritten', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
