# Generated by Django 5.1 on 2024-09-09 08:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannelFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('channel_name', models.CharField(max_length=200)),
                ('success', models.BooleanField(default=False)),
                ('exception', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.newssource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NewsApiFetchLog',
        ),
    ]
