# Generated by Django 5.1 on 2024-09-08 01:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='articlerecord',
            constraint=models.UniqueConstraint(fields=('source', 'title'), name='unique_source_title'),
        ),
    ]
