# Generated by Django 5.1 on 2024-09-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecord',
            name='title_bad_words',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
