# Generated by Django 5.1 on 2024-09-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlerecord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecord',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
