# Generated by Django 5.1 on 2024-09-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_newschannelfetchlog_delete_newsapifetchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlerecord',
            name='fetch_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.newschannelfetchlog'),
        ),
    ]
