# Generated by Django 5.1 on 2024-09-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlerecord_fetch_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecord',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='articlerecord',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlerecord',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
