# Generated by Django 5.1 on 2024-09-08 02:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlerecord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiedarticlerecord',
            old_name='original',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='modifiedarticlerecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
